// Environment Controls
export const TOGGLE_BACKGROUND = "TOGGLE_BACKGROUND";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_ENVIRONMENT_OPTION = "SET_ENVIRONMENT_OPTION";
//

// Projects
export const NEW_PROJECT = "NEW_PROJECT";
export const UPDATE_PROJECT_DETAILS = "UPDATE_PROJECT_DETAILS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const POPULATE_PROJECTS = "POPULATE_PROJECTS";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_PROJECT_START = "SET_PROJECT_START";
export const SET_PROJECT_END = "SET_PROJECT_END";
//

// Themes
export const SET_THEME = "SET_THEME";

// Mode selector
export const MODE_SELECT = "MODE_SELECT";
//

// Current Model
export const SET_MODEL = "SET_MODEL";
export const SET_FOV = "SET_FOV";
export const SET_FAR = "SET_FAR";
export const SET_NEAR = "SET_NEAR";
export const SET_SIZE_BOUNDING = "SET_SIZE_BOUNDING";
export const SET_BOX = "SET_BOX";
//

// Camera Controls
export const SET_CAMERA_MODE = "SET_CAMERA_MODE";
//

// Extra Controls
export const TOGGLE_LOCK = "TOGGLE_LOCK";
export const TOGGLE_BOUNDING_BOX = "TOGGLE_BOUNDING_BOX";
export const TOGGLE_AXIS = "TOGGLE_AXIS";
export const TOGGLE_AUTOROTATE = "TOGGLE_AUTOROTATE";
//

// Material Controls
export const SET_SELECTED_MATERIAL = "SET_SELECTED_MATERIAL";
// Media State
export const SET_MEDIA_MODEL = "SET_MEDIA_MODEL";
export const SET_MEDIA_FOV = "SET_MEDIA_FOV";
export const SET_MEDIA_FAR = "SET_MEDIA_FAR";
export const SET_MEDIA_NEAR = "SET_MEDIA_NEAR";
export const SET_MEDIA_SIZE_BOUNDING = "SET_MEDIA_SIZE_BOUNDING";
export const SET_MEDIA_BOX = "SET_MEDIA_SET_BOX";
export const SET_MEDIA_ENV_BACKGROUND = "SET_MEDIA_ENV_BACKGROUND";
export const SET_MEDIA_SOLID_BACKGROUND = "SET_MEDIA_SOLID_BACKGROUND";
export const RESET_MEDIA_STATE = "RESET_MEDIA_STATE";
//

// Media Controls
export const TOGGLE_MEDIA_ENV_B = "TOGGLE_MEDIA_ENV_B";
export const TOGGLE_MEDIA_SOLID_B = "TOGGLE_MEDIA_SOLID_B";
export const TOGGLE_MEDIA_NO_B = "TOGGLE_MEDIA_NO_B";
export const TOGGLE_MEDIA_LOCK = "TOGGLE_LOCK";
export const TOGGLE_MEDIA_BOUNDING_BOX = "TOGGLE_BOUNDING_BOX";
export const TOGGLE_MEDIA_AXIS = "TOGGLE_AXIS";
export const TOGGLE_MEDIA_AUTOROTATE = "TOGGLE_AUTOROTATE";
export const SET_MEDIA_SPHERE = "SET_MEDIA_SPHERE";
export const SET_MEDIA_KEY_LIGHT = "SET_MEDIA_KEY_LIGHT";
export const SET_MEDIA_BACK_WALL = "SET_MEDIA_BACK_WALL";
export const SET_MEDIA_GROUND_POLE = "SET_MEDIA_GROUND_POLE";
export const RESET_MEDIA_CONTROLS = "RESET_MEDIA_CONTROLS";
//
