// Environment Controls
export const TOGGLE_BACKGROUND = "TOGGLE_BACKGROUND";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
//

// Projects
export const UPDATE_PROJECT_DETAILS = "UPDATE_PROJECT_DETAILS";
export const DELETE_PROJECT = "DELETE_PROJECT";
//
